name = "ObjectPools"
uuid = "24f22195-99b9-48e5-af12-d1e7e5a5310e"
authors = ["Schaffer Krisztian <schaffer.krisztian@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[compat]
BenchmarkTools = "0.5"
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
